# Generated by Django 5.1.2 on 2024-12-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_attendees_members_eventattendee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees_members',
        ),
        migrations.RemoveField(
            model_name='eventattendee',
            name='registered_at',
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='email',
            field=models.EmailField(default='<holyhub@gmail.com>', max_length=254),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='name',
            field=models.CharField(default='john', max_length=100),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='phone',
            field=models.CharField(default='07********', max_length=15),
        ),
    ]
