# Generated by Django 5.1.2 on 2024-12-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventsattendee_delete_attendee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsattendee',
            name='confirmed_at',
        ),
        migrations.AlterField(
            model_name='eventsattendee',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
