# Generated by Django 5.1.2 on 2024-12-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_eventsattendee_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventsattendee',
            table='eventsattendee',
        ),
    ]
