# Generated by Django 5.1.2 on 2024-11-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='link_message',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
