# Generated by Django 5.1.2 on 2024-11-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0007_calltoaction_link_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=128)),
                ('password2', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='members/')),
            ],
        ),
    ]
