# Generated by Django 5.1.2 on 2024-11-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0008_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='member',
            name='password2',
        ),
    ]
